name: popover
description: A popover is a transient view that appears above other content onscreen when you tap a control or in an area.
version: 0.3.0
homepage: https://github.com/minikin/popover

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.5'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
